/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HelloWorldAbi__factory } from "./HelloWorldAbi__factory";
export { XCallAbi__factory } from "./XCallAbi__factory";
