/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloWorldAbi } from "./HelloWorldAbi";
export type { XCallAbi } from "./XCallAbi";
export * as factories from "./factories";
export { HelloWorldAbi__factory } from "./factories/HelloWorldAbi__factory";
export { XCallAbi__factory } from "./factories/XCallAbi__factory";
